### ISSUE TITLE
Bug .

### ISSUE THREAD

**Issue by DogancanYr** [Altansar69/CS.RIN.RU-Enhanced-external#5]
Cs.rin.ru also exists and steamdb shows it correctly, but steam does not.

https://steamdb.info/app/601360/charts
https://store.steampowered.com/app/601360/Portal_Revolution/?curator_clanid=4777282

**Comment by Altansar69** [comment]
So we need to find a better way of detecting whether it's a game or DLC.
I tried this: 
const pageUrl = !document.querySelector("#game_highlights > div.rightcol.as-side-details > div > div.glance_details") ? document.location.pathname // Game page
        : document.querySelector("#game_highlights > div.rightcol.as-side-details > div > div.glance_details > p > a").getAttribute("href"); // DLC Page
        
        It works perfectly in the browser console. But not in the script. In fact, the part I'm looking at to see if it's DLC seems to load on the Steam page a little after the script executes this line.

**Comment by Altansar69** [comment]
Well done on your find, by the way

**Comment by Altansar69** [comment]
But that's the problem!
The right id is not 620.
The case of mods is not foreseen, the script believes that it is a DLC and so instead of taking its id which is 601360 it does as for DLC i.e. take the ID of its parent which is 620 (the id of portal 2 games).
That's why there's an error only on Steam and not on SteamDB, because on SteamDB the appid retrieved from the page is the right one, but not on Steam, where our selector didn't take this particular case into account. As you said, the search id is 620, which is precisely wrong.

Translated with www.DeepL.com/Translator (free version)

**Comment by SubZeroPL** [comment]
Maybe we could use the Steam/SteamDB page url to search for rin topic? The url should be present in the first post of each game topic (see [FAQ](https://cs.rin.ru/forum/viewtopic.php?f=30&t=98158) Question E01).

**Comment by Altansar69** [comment]
We thought of this @SubZeroPL, the problem is that the / in the url breaks the search and there's no way to fix it (I've asked Ressourector), which is why we only use the appid

**Comment by Altansar69** [comment]
haha in same time

**Comment by Altansar69** [comment]
Because we need to find a way to differentiate between games and DLC on a Steam page, without mods being considered as DLC.
We're currently checking whether this square exists (purple).
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/a753550b-e84a-42a6-bf4c-0c8ed00c6923)
Except that it also exists for mods, hence the problem.
I thought of a solution: check if this square exists on the right.
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/d7dde498-e8a1-4735-b296-327f04e38bc5)
It only exists for DLC, not mods. The problem is that the code works in the browser console but not in the script. I think this little square on the right isn't on the basic HTML page, Steam must add it afterwards (and therefore after the userscript has been executed).


So we need to find another way to differentiate them.
I thought of something quite simple. Return to the initial solution.
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/74b84073-2d92-4371-be51-e40e7a622147)


See if this square exists. If it does, then we're either on DLC or a mod. Then we just have to decide between the 2.
We can't search for text because each user has a different language (otherwise we could have searched for the word "mods").
But there is something common to all mods in all languages.

![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/de969a22-c985-4bea-a945-219099eb51d8)
on the second line you can see the word "ici" (here) with a href. You have the equivalent in your language.
On all mods in all languages this href is: https://store.steampowered.com/about/communitymods/?snr=1_5_9_
(maybe not the part with the "?" at the end - check)
So we can just check if there is this href in the paragraph. If so, act like a GAME (i.e. take the appid from the url).

**Comment by Altansar69** [comment]
Redpoint

**Comment by Altansar69** [comment]
Gj
